[phases.setup]
nixPkgs = ['php', 'nodejs', 'sqlite', 'mariadb']

[phases.build]
cmds = [
  'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer',  # Instalar Composer
  'composer install --no-dev --optimize-autoloader',  # Ejecutar composer install
  'npm install && npm run build'  # Instalar dependencias de Node.js y ejecutar la construcción
]

[phases.start]
cmds = [
  'php artisan migrate --force',
  'php artisan serve --host 0.0.0.0 --port $PORT'
]
