[phases.setup]
nixPkgs = ['php', 'nodejs', 'sqlite', 'mariadb']

[phases.build]
cmds = [
  'curl -sS https://getcomposer.org/installer | php',
  'php composer.phar install --no-dev --optimize-autoloader',
  'npm install',
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[phases.start]
cmds = [
  'until php artisan migrate --force; do echo "Waiting for database..."; sleep 3; done',
  'php artisan serve --host 0.0.0.0 --port $PORT'
]
