[phases.setup]
nixPkgs = ['php', 'nodejs', 'sqlite', 'mariadb']

[phases.build]
cmds = [
  'curl -sS https://getcomposer.org/installer | php',
  'php composer.phar install --no-dev --optimize-autoloader',
  'npm install && npm run build'
]

[phases.start]
cmds = [
  'php artisan migrate --force',
  'php artisan serve --host 0.0.0.0 --port $PORT'
]
